// Builds dist/Fluke287.html: index.html with every module in src/ and the Fluke logo inlined, so it is one file
// to upload. The page still expects the website's own site-nav.js and images/logo.png next to it (header, logo,
// menu), and shows a plain fallback header if they are missing.
//   node scripts/build.mjs
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const entry = 'app';

const IMPORT = /import\s*\{([^}]*)\}\s*from\s*'\.\/([\w-]+)\.js';?\n?/g;
const EXPORT_NAME = /^export\s+(?:async\s+)?(?:function\*?|class|const|let|var)\s+([A-Za-z_$][\w$]*)/gm;

const modules = new Map(); // name -> { code, imports: [{names, from}], exports: [names] }

async function load(name) {
  if (modules.has(name)) return;
  const source = await readFile(join(root, 'src', `${name}.js`), 'utf8');
  const imports = [...source.matchAll(IMPORT)].map((m) => ({
    names: m[1].split(',').map((s) => s.trim()).filter(Boolean),
    from: m[2],
  }));
  const exports = [...source.matchAll(EXPORT_NAME)].map((m) => m[1]);
  if (/^export\s+(default|\{)/m.test(source)) throw new Error(`${name}.js uses an export form the build does not handle`);
  const code = source.replace(IMPORT, '').replace(/^export\s+/gm, '');
  modules.set(name, { code, imports, exports });
  for (const dep of imports) await load(dep.from);
}

await load(entry);

// Dependencies first.
const order = [];
const seen = new Set();
const visit = (name) => {
  if (seen.has(name)) return;
  seen.add(name);
  modules.get(name).imports.forEach((d) => visit(d.from));
  order.push(name);
};
visit(entry);

// Each module becomes a function scope, so top-level names in different files cannot collide.
const bundle = order
  .map((name) => {
    const { code, imports, exports } = modules.get(name);
    const pulls = imports.map((d) => `const { ${d.names.join(', ')} } = __modules[${JSON.stringify(d.from)}];`).join('\n  ');
    return `__modules[${JSON.stringify(name)}] = (() => {\n  ${pulls}\n${code}\n  return { ${exports.join(', ')} };\n})();`;
  })
  .join('\n\n');

let html = await readFile(join(root, 'index.html'), 'utf8');
const logo = (await readFile(join(root, 'images', 'fluke-seeklogo.svg'))).toString('base64');

const scriptTag = '<script type="module" src="src/app.js"></script>';
if (!html.includes(scriptTag)) throw new Error('index.html no longer loads src/app.js as expected');
html = html
  .replace(scriptTag, `<script>\n(() => {\nconst __modules = {};\n${bundle}\n})();\n</script>`)
  .replace('src="images/fluke-seeklogo.svg"', `src="data:image/svg+xml;base64,${logo}"`)
  .replace('</title>', '</title>\n<link rel="icon" href="images/logo.png">')
  .replace('<!doctype html>', '<!doctype html>\n<!-- Generated by scripts/build.mjs from https://github.com/bvksound/FlukeViewForms. Edit the sources, not this file. -->');

await mkdir(join(root, 'dist'), { recursive: true });
await writeFile(join(root, 'dist', 'Fluke287.html'), html);
console.log(`dist/Fluke287.html  ${(html.length / 1024).toFixed(0)} KB  (${order.length} modules inlined)`);
