"""Regenerates src/logos.js: the Fluke and BVK logos as small JPEG data URLs (PDF reports embed JPEG directly).
Needs PyMuPDF:  python3 scripts/make-logos.py"""
import base64, os
import fitz

root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def flatten(path, width, height, quality=90):
    """The image scaled to width x height onto white (transparency becomes white), as JPEG bytes."""
    doc = fitz.open()
    page = doc.new_page(width=width, height=height)
    page.draw_rect(page.rect, fill=(1, 1, 1), color=None)
    page.insert_image(page.rect, filename=os.path.join(root, path))
    return page.get_pixmap(dpi=72).tobytes('jpeg', jpg_quality=quality)


def data_url(jpeg):
    return 'data:image/jpeg;base64,' + base64.b64encode(jpeg).decode()


fluke = flatten('images/fluke-seeklogo.png', 600, 121)
bvk = flatten('images/bvk-logo.png', 128, 128)
with open(os.path.join(root, 'src', 'logos.js'), 'w') as f:
    f.write('// Generated by scripts/make-logos.py from images/fluke-seeklogo.png and images/bvk-logo.png. Do not edit.\n')
    f.write('// The Fluke logo is a Fluke trademark, used to identify the supported meter; see the README.\n')
    f.write(f'export const FLUKE_LOGO = {data_url(fluke)!r};\n')
    f.write(f'export const BVK_LOGO = {data_url(bvk)!r};\n')
print('fluke', len(fluke), 'bytes; bvk', len(bvk), 'bytes')
